language: python
python:
- '2.7'
env:
- DJANGO=1.8
before_install: echo 'started tests'
- cp samaweb/local_settings.py samaweb/settings.py
install:
- pip install -q Django==$DJANGO --use-mirrors
- pip install https://github.com/dcramer/pyflakes/tarball/master
- pip install -r requirements.txt
- pip install coveralls
before_script:
- pyflakes -x W src
script:
- python manage.py test
- coverage run --source=api,samacore,samaweb manage.py test
- coverage report -m
after_success: coveralls
before_deploy: echo 'beginning of the deployment'
- cp samaweb/deploy_settings.py samaweb/settings.py
deploy:
  provider: heroku
  on:
    all_branches: true
  api_key:
    secure: QN/vKMtjNOFEThcbMKSH47ne3eU5+KpRMbKmA5DKtYXcHZvsWH3SHoyt5Q8xrfqiJZQhv219QPVGLesjcESX2Ytlaf5NkRfFgP6I+pGVNBFPrwz+h9eIRDoxw/FxFcOHn8cd6mt+gG87aelf/vPzgXNgmiKZpUnQ+1VQ9T8EWe4=
after_deploy:
- echo 'Deployment ended'
